### ISSUE TITLE
Fresh container setup fails, errors of no network connectivity ?

### ISSUE THREAD

**Issue by xBeEatNUx** [Renegade-Master/zomboid-dedicated-server#50] opened 2022-11-14 21:56 UTC
**Describe the bug**
Pulling a new image and setting up the docker container fails which seems to be due to not able to load the public/steambootstrapper ? It eventually complains off file manifest issues the network connection. The cluster works fine in terms of network as I created other games and other services with no issues. 

I am using portainer for my docker management. 

Seems to be really related to Zomboid.

**To Reproduce**
1.  Pull Image
2. Build container from said image and include exposed ports and mount the persistent volumes
3. check logs for failure.

**Screenshots**
Check Log

**Desktop (please complete the following information):**
 - OS: Debian
 - Docker Version 20.10.21
 - Image Version latest

**Additional context**
check log, doesnt really go into detail 
[_dedicated-project-zomboid_logs.txt](https://github.com/Renegade-Master/zomboid-dedicated-server/files/10007389/_dedicated-project-zomboid_logs.txt)

**Comment by Renegade-Master** [comment] 2022-11-14 21:59
That is definitely an issue with Steam CMD not being able to connect. It can't even check if it is up to date, nevermind anything Zomboid related.

**Comment by Renegade-Master** [comment] 2022-11-14 22:02
Can you confirm that the following works? I tested the latest version earlier today
https://github.com/Renegade-Master/zomboid-dedicated-server/issues/48#issuecomment-1314266550

**Comment by TetrisBlack** [comment] 2022-11-14 22:39
I can reproduce, server does not start. 
![image](https://user-images.githubusercontent.com/9931484/201783041-eb4cae05-78f0-4a92-be0d-86bf9c767aa1.png)

**Comment by xBeEatNUx** [comment] 2022-11-14 22:41
> 

my ports are setup proper but also pulling 2.3.0 doesnt work either.

**Comment by xBeEatNUx** [comment] 2022-11-16 06:58
@Renegade-Master any thoughts how to get around this?

**Comment by Straskal** [comment] 2022-11-18 13:56
> I can reproduce, server does not start.
> 
> ![image](https://user-images.githubusercontent.com/9931484/201783041-eb4cae05-78f0-4a92-be0d-86bf9c767aa1.png)

Hey Tetris, the screenshot you posted seems to be a different issue than what xBeEatNUx is having.

I was seeing the same "failed to connect to steam servers" error and seemed to fix it by removing the BIND_IP env variable.

Hope that helps

**Comment by xBeEatNUx** [comment] 2022-11-18 15:14
> > I can reproduce, server does not start.
> > ![image](https://user-images.githubusercontent.com/9931484/201783041-eb4cae05-78f0-4a92-be0d-86bf9c767aa1.png)
> 
> Hey @TetrisBlack, the screenshot you posted seems to be a different issue than what xBeEatNUx is having.
> 
> I was seeing the same "failed to connect to steam servers" error and seemed to fix it by removing the BIND_IP env variable.
> 
> Hope that helps

Ooooooo that’s interesting, let me try that. I’ve pushed the docker image without hat env all together so wonder if there’s a way to run it without that being created

**Comment by Straskal** [comment] 2022-11-18 15:54
@xBeEatNUx I'm sorry for the confusion 😕  that BIND_IP fix was directed at Tetris.

I was looking at your log file as well and i'm not entirely sure why SteamCMD itself is giving you grief..

**Comment by xBeEatNUx** [comment] 2022-11-18 16:04
> @xBeEatNUx I'm sorry for the confusion 😕 that BIND_IP fix was directed at Tetris.
> 
> I was looking at your log file as well and i'm not entirely sure why SteamCMD itself is giving you grief..

Damn I got excited for a sec lol.

**Comment by xBeEatNUx** [comment] 2022-11-18 18:12
@Renegade-Master Seems like this was an issue definitely with steam and how the container reaches its services, not sure why it came back up. Are you able to run a new container with no issues?

I can into a possible fix but the container crashes so I cant connect to it to test.

https://github.com/ValveSoftware/steam-for-linux/issues/7667

**Comment by Renegade-Master** [comment] 2022-11-18 18:35
This image doesn't do anything with Networking. It doesn't even expose its own ports without the User specifying them.

I cannot really do anything to correct this. It is down to Steam to fix the issue.
At least we have the Issue that you linked to follow this, but for now I am going to close this Issue as it belongs with Steam, not here 🙂

If you disagree though, we can maybe keep it open if there is something that I can do to correct this.

**Closed by Renegade-Master** 2022-11-18 18:35 UTC
Labels: bug

**Comment by xBeEatNUx** [comment] 2022-11-18 18:52
I was hoping we could come to a resolution and I can atleast get this working again. Not sure if people are having the issue and not reporting or just doing something else. While I like the project, I’m sure others are running into the same issue so was hoping WE could come up with a solution instead of hosting a broken image.

**Comment by xBeEatNUx** [comment] 2022-11-18 18:53
This pretty much started when 41.78 arrived so whole knows if it’s all related. I’m just trying to get to the bottom of it

**Comment by Renegade-Master** [comment] 2022-11-18 20:15
But it works fine for me still. It isn't broken. I can't control the part that isn't working

**Comment by Renegade-Master** [comment] 2022-11-18 20:28
I just tried it again myself from a basic Oracle x86 host. 

It only has 2 vCPU and 1 GB of Memory so it took a few attempts to get it going, but it works fine. I can connect, and it plays.

**Comment by xBeEatNUx** [comment] 2022-11-18 20:35
So you were able to pull the latest imagine and the script all works fine from a fresh setup ?

**Comment by Renegade-Master** [comment] 2022-11-18 20:38
Yes. Although it will crash due to low resource availability on the host several times during startup.

But on restarting (`docker start zomboid-server`), it picks up where it left off and eventually starts. I have never once seen this Steam connection issue myself _except_ for situations like on a Wednesday 00:00 GMT when Steam likes to do maintenance cycles.

I did not mean to appear to dismiss your troubles here by the way. It just really seems to be an issue between your PC/VPS and Steam, which is an area that I cannot really control.

**Comment by xBeEatNUx** [comment] 2022-11-21 18:02
So for giggles, I built a new server running proxmox and docker and went through this again. Same issue, one my reddit post someone else is having the issue so I don't believe its related to my server since I have the same issue on 2 of them and another user is having the same issue. 

Possible it could be related to the ISP and connectivity to steam but I just ran through steamCMD pulling Satisfactory with ZERO issues. Check the log below, t goes through a similar steamCMD process but this completes successfully. 

[Reddit link to error, another user explains he has the same issue](https://www.reddit.com/r/projectzomboid/comments/yv8dwk/comment/ix2gsoi/?context=3)
[sat.txt](https://github.com/Renegade-Master/zomboid-dedicated-server/files/10059306/sat.txt)

**Comment by xBeEatNUx** [comment] 2022-11-21 18:02
The sat.txt is the logs btw

**Comment by Renegade-Master** [comment] 2022-11-22 01:43
I

**Comment by Renegade-Master** [comment] 2022-11-22 10:13
And a fresh deployment of this image still doesn't work?

Is there any chance that you have some misconfiguration with DNS specifically in Docker?

Try running the image with:

```sh
docker run --detach \                    
       --mount type=bind,source="$(pwd)/ZomboidDedicatedServer",target=/home/steam/ZomboidDedicatedServer \
       --mount type=bind,source="$(pwd)/ZomboidConfig",target=/home/steam/Zomboid \
       --publish 16261:16261/udp --publish 16262:16262/udp --publish 27015:27015/tcp \
       --dns="1.0.0.1" \
       --name zomboid-server \
       docker.io/renegademaster/zomboid-dedicated-server:2.3.0 
```
