### ISSUE TITLE
/home/steam/steamcmd.sh: line 38:    20 Segmentation fault      (core dumped) $DEBUGGER "$STEAMEXE" "$@" and more!

### ISSUE THREAD

**Issue by DoomOfMax97** [Renegade-Master/zomboid-dedicated-server#24] opened 2022-06-23 19:36 UTC
**Describe the bug**

**To Reproduce**
1. Cloned repository.
2. Built image with **"docker compose up --build**
3. Started image using **"docker compose up --build**
4. See attached error:
**See end of post.**

**Expected behavior**
The Server to launch properly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu Server]
 - Docker Version [

>  Client: Docker Engine - Community
>  Version:           20.10.17
>  API version:       1.41
>  Go version:        go1.17.11
>  Git commit:        100c701
>  Built:             Mon Jun  6 23:02:57 2022
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.17
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.17.11
>   Git commit:       a89b842
>   Built:            Mon Jun  6 23:01:03 2022
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.6
>   GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
>  runc:
>   Version:          1.1.2
>   GitCommit:        v1.1.2-0-ga916309
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
]

 - Image Version [master]

**Additional context**

**Installed docker using "curl -fsSL https://get.docker.com -o get-docker.sh"** (And running it)
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Setting variables...
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/run_server.sh: line 187: /home/steam/Zomboid/ip.txt: Permission denied
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Updating Folder Permissions...
> zomboid-dedicated-server-zomboid-server-1  | chown: changing ownership of '/home/steam/ZomboidDedicatedServer': Operation not permitted
> zomboid-dedicated-server-zomboid-server-1  | chown: changing ownership of '/home/steam/Zomboid': Operation not permitted
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Folder Permissions updated.
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Applying Pre Install Configuration...
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Pre Install Configuration applied.
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Updating Project Zomboid Server...
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/steamcmd.sh: line 38:    20 Segmentation fault      (core dumped) $DEBUGGER "$STEAMEXE" "$@"
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Project Zomboid Server updated.
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Checking if this is the first run...
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### This is the first run.
> zomboid-dedicated-server-zomboid-server-1  | Starting server for 60 seconds
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Starting Project Zomboid Server...
> zomboid-dedicated-server-zomboid-server-1  | timeout: failed to run command '/home/steam/ZomboidDedicatedServer/start-server.sh': No such file or directory
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Project Zomboid Server stopped.
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### First run check complete.
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Applying Post Install Configuration...
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  | /home/steam/Zomboid/Server/ZomboidServer.ini not found!
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Post Install Configuration applied.
> zomboid-dedicated-server-zomboid-server-1  | sed: can't read /home/steam/ZomboidDedicatedServer/ProjectZomboid64.json: No such file or directory
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Starting Project Zomboid Server...
> zomboid-dedicated-server-zomboid-server-1  | timeout: failed to run command '/home/steam/ZomboidDedicatedServer/start-server.sh': No such file or directory
> zomboid-dedicated-server-zomboid-server-1  |
> zomboid-dedicated-server-zomboid-server-1  | ### Project Zomboid Server stopped.
> zomboid-dedicated-server-zomboid-server-1 exited with code 0

**Comment by Renegade-Master** [comment] 2022-06-23 22:44
Hello!

Looks like a permissions issue.

If you type 
```shell
ls -lan
```

are the folders `ZomboidConfig`, and `ZomboidDedicatedServer` listed as belonging to your user?

**Comment by DoomOfMax97** [comment] 2022-06-23 23:29
Yep I think so

> michael@michael:~/ProjectZomboid/zomboid-dedicated-server$ ls -lan
> total 96
> drwxrwxr-x 8 1000 1000  4096 Jun 23 19:28 .
> drwxrwxr-x 3 1000 1000  4096 Jun 23 19:28 ..
> drwxrwxr-x 2 1000 1000  4096 Jun 23 19:31 docker
> -rw-rw-r-- 1 1000 1000  2024 Jun 23 19:28 docker-compose.yaml
> -rw-rw-r-- 1 1000 1000    27 Jun 23 19:28 .dockerignore
> drwxrwxr-x 8 1000 1000  4096 Jun 23 19:28 .git
> drwxrwxr-x 4 1000 1000  4096 Jun 23 19:28 .github
> -rw-rw-r-- 1 1000 1000  2616 Jun 23 19:28 .gitignore
> -rw-rw-r-- 1 1000 1000 35413 Jun 23 19:28 LICENSE
> -rw-rw-r-- 1 1000 1000 15836 Jun 23 19:28 README.md
> drwxrwxr-x 2 1000 1000  4096 Jun 23 19:28 src
> drwxrwxr-x 2 1000 1000  4096 Jun 23 19:28 ZomboidConfig
> drwxrwxr-x 2 1000 1000  4096 Jun 23 19:28 ZomboidDedicatedServer

**Comment by Renegade-Master** [comment] 2022-06-24 17:00
Strange.

Out of interest, were you using 
`docker-compose up`
or
`docker compose up`

I use the standalone [Docker-Compose|https://github.com/docker/compose/releases/latest]. I am not sure if there is complete feature parity between `docker-compose` and `docker compose`.

Apart from that though, I can't see why this isn't working.

- [ ] Make sure you are not the `root` user, or using `sudo`
- [ ] Make sure that you do not run any Docker or Docker-Compose commands with `sudo`
- [ ] Delete `ZomboidConfig`, and `ZomboidDedicatedServer` directories and recreate them manually
- [ ] Run `docker-compose down; docker-compose up --detach; docker-compose logs --follow`

Do the issues persist?

**Comment by corp-0** [comment] 2022-06-27 02:31
I have the same exact issue, I'm running with the new ``docker compose`` command in Ubuntu 22.04. What do you mean not using sudo when invoking ``docker compose`` commands? docker requires ``sudo``

**Comment by DoomOfMax97** [comment] 2022-06-27 15:32
@Renegade-Master I was using 'docker compose up', without sudo, I installed docker from here: https://docs.docker.com/engine/install/ubuntu/

[x] Make sure you are not the root user, or using sudo*
[x] Make sure that you do not run any Docker or Docker-Compose commands with sudo
[x] Delete ZomboidConfig, and ZomboidDedicatedServer directories and recreate them manually
[x] Run docker-compose down; docker-compose up --detach; docker-compose logs --follow**
* I am the user I created during the ubuntu install, but I need to run commands with sudo to run them as an admin.
** had to use 'docker compose' instead of 'docker-compose'.
[log.txt](https://github.com/Renegade-Master/zomboid-dedicated-server/files/8993300/log.txt)

@corp-0 You can and you *should* for security reasons, but as far as I can tell for now it's a bit of a hassle.
(As in I haven't found an easy way that works flawlessly yet, but haven't looked that much either.)

**Comment by Renegade-Master** [comment] 2022-06-27 18:49
@corp-0 @DoomOfMax97 

So, you run Docker at least without having to type `sudo` by following the "[Post Installation Steps](https://docs.docker.com/engine/install/linux-postinstall/)". Basically this means adding your user (**who is not the `root` user**) to the "docker" group (or more accurately: whatever group the `/var/run/docker.sock` socket is assigned to). Alternatively, you have to install Docker in "[rootless-mode](https://docs.docker.com/engine/security/rootless/)", which is a bit more work.

`docker compose` is not `docker-compose`. Functionality was somewhat merged recently, but they are not the exact same thing (as far a I know). You get the Docker-Compose binaries from the [Docker-Compose](https://github.com/docker/compose/releases/latest) Releases page.

**Comment by DoomOfMax97** [comment] 2022-06-27 18:55
I also installed the rootless-mode-package, if they are different that would explain it, I am currently setting up a new debian vm anyways, so I'll use the binary you mentioned directly and see how it goes.

**Comment by Renegade-Master** [comment] 2022-06-28 23:16
I hope it works. Make sure to clone the repo down into a new folder to really start from scratch.

Aside from that, I really can't tell what is causing your issue.

**Comment by DoomOfMax97** [comment] 2022-06-29 08:27
It seems like it is an issue with the steam-cmd-image, since I tried it on a fresh install
and I still get the same issue (Segmention fault).
Is it possible that it is an issue with the steam-cmd-image itself?
Are you able to run the container from scratch?
The permission issues seem to be fixed now, creating the docker user or more precisely the group was actually necessary,
I thought I could just run the rootless script, thx for the tip.
[log.txt](https://github.com/Renegade-Master/zomboid-dedicated-server/files/9008671/log.txt)

**Comment by Renegade-Master** [comment] 2022-06-29 18:41
> Are you able to run the container from scratch?

Every commit actually runs through a pipeline here.
A VM is created from scratch. Docker/-Compose is installed, and my repository is cloned down. Then the server is started with a custom configuration, and the configuration is validated at the end.

- You can see all of the previous runs here: [link](https://github.com/Renegade-Master/zomboid-dedicated-server/actions/workflows/docker-build.yml)
- Here is one I kicked off just now to do a fresh install: [link](https://github.com/Renegade-Master/zomboid-dedicated-server/runs/7118238845?check_suite_focus=true#step:7:984)

The only things I can see about SegFaults from the SteamCMD script seem to have been caused by running on ARM architecture, or trying to use SteamCMD without having installed the prerequisites first.

The LinuxGSM (which is a pretty popular server manager) has [this advice](https://docs.linuxgsm.com/faq#how-do-i-solve-a-segmentation-fault), but I don't think that applies to this situation too well.

**Comment by Renegade-Master** [comment] 2022-06-30 21:44
I notice that you printed your user and group IDs, but you didn't appear to change them in the `docker-compose.yaml` file.

```shell
dz@dangerzonelinux:~/zomboid-dedicated-server$ printf "UID: %s\nGID: %s\n" $(id -u) $(id -g)
UID: 1000
GID: 999
``` 

You need to change the values at the following keys to your UID and GID:

```yaml
services:
  zomboid-server:
    build:
      ...
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    ...
    user: "1000:1000"
```

I also notice that for some reason, the `src`, `ZomboidConfig`, `ZomboidDedicatedServer` directories don't seem to be present:

```shell
dz@dangerzonelinux:~/zomboid-dedicated-server$ mkdir ZomboidConfig ZomboidDedicatedServer
dz@dangerzonelinux:~/zomboid-dedicated-server$ ls
docker  docker-compose.yaml  LICENSE  README.md

```

I don't know if any of these are your problem, but they look wrong to me

**Comment by Renegade-Master** [comment] 2022-07-02 14:30
If you want to bypass my starting image, you would probably need to do the following:

1. Clone down the [zomboid-dedicated-server](https://github.com/Renegade-Master/zomboid-dedicated-server.git) and [steamcmd-minimal](https://github.com/Renegade-Master/steamcmd-minimal.git) repos.
2. Download the following two Dockerfiles, and replace the ones in the repos with these modified versions.
[zomboid-dedicated-server.dockerfile](https://github.com/Renegade-Master/zomboid-dedicated-server/files/9033098/zomboid-dedicated-server.txt)
[steamcmd-minimal.dockerfile](https://github.com/Renegade-Master/zomboid-dedicated-server/files/9033099/steamcmd-minimal.txt)
3. Build the `steamcmd-minimal` image with the following command:
```shell
docker build -f docker/steamcmd-minimal.Dockerfile -t renegademaster/steamcmd-minimal:1.0.0-dirty --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) .
```

You shouldn't have to change anything in the `docker-compose.yaml` file because it just builds whatever is in the repo, and you should have changed the `docker/steamcmd-minimal.Dockerfile`.

**Comment by Renegade-Master** [comment] 2022-07-02 14:34
In theory, you could use anyone's SteamCMD image as long as you remember to put this line near the top of the `zomboid-dedicated-server.dockerfile` 
```dockerfile
ENV STEAM_PATH=<path_to_steamcmd.sh>
```

That way the `zomboid-dedicated-server` container can find the SteamCMD executable.

**Comment by DoomOfMax97** [comment] 2022-07-29 16:20
Hi, sorry for the late reply, was quite busy myself, when I try to build the SteamCMD image, after replacing the file, I get the following error:
[error.log](https://github.com/Renegade-Master/zomboid-dedicated-server/files/9221627/error.log)

**Comment by Renegade-Master** [comment] 2022-07-29 19:28
Oh hey, I didn't expect you to come back. I was just trying to fix the ticket 😅

Have you tried with the new SteamCMD image (1.1.1)?
https://github.com/Renegade-Master/steamcmd-minimal/pkgs/container/steamcmd-minimal

**Comment by DoomOfMax97** [comment] 2022-07-30 00:21
Hi :)

Neato, I'll give it a shot in ~16h, for some reason I couldn't even get steamcmd to run on my vm (no docker),
tbh my plan B is to just give up and use a windows VM bc installing SteamCMD (no docker) works there for some reason.

**Comment by Renegade-Master** [comment] 2022-07-30 15:12
Very strange indeed. I actually switched over to Buildah for building and Podman for running recently. Still use Docker in the GitHub Action tests to ensure compatibility though. I do all of my development in either a Fedora or Ubuntu VM.

SteamCMD does have some weird dependency issues. You have to [manually enable 32-bit libraries](https://github.com/Renegade-Master/steamcmd-minimal/blob/main/docker/steamcmd-minimal.Dockerfile#L30) for example because SteamCMD was never updated to use 64-bit architectures.

**Closed** 2022-08-08 23:27 UTC
Labels: bug

**Comment by Renegade-Master** [comment] 2022-08-08 23:29
Please comment or reopen if your issue still exists in the most recent version: 2.0.0
